name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Autoconf
      run: sudo apt-get update && sudo apt-get install -y autoconf
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Checkout chomik dependency
      uses: actions/checkout@v4
      with:
        repository: pawelbiernacki/chomik
        path: ./chomik

    - name: Build libchomik
      run: cd ./chomik && ./configure && make

    - name: Install libchomik
      run: cd ./chomik && make install

    - name: configure
      run: ./configure --enable-chomik-servers --enable-sdl-chomik

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
